### ISSUE TITLE
unicode error in python2.6

### ISSUE THREAD

**Issue by zhangyangyu** [banjiewen/bernhard#13]
In python2.6, adding custom fields with `"attributes": {}` will cause error if value in the dict is not ascii because `str(value[key])` is used. We can use `unicode` but in python3.x this will cause error.

**Comment by kainz** [comment]
This is one of the [common usecases](https://pythonhosted.org/six/#six.text_type) covered in `six`, the python 2/3 compatibility helper. in this case, a good fix is to use `six.text_type(val)`.

**Comment by zhangyangyu** [comment]
Yes you are right. But when I opened this issue, I just wanted to solve the bug non-ascii strings can not be used in attributes, not meant to make it 2/3 compatible, though I said in python3.x this will cause error. Now it seems this package has been made 2/3 compatible.
