### ISSUE TITLE
Error on Windows: AttributeError: 'module' object has no attribute 'MSG_WAITALL'

### ISSUE THREAD

**Issue by npezolano** [banjiewen/bernhard#15]
This error occurs when trying to send from a windows client to a Linux Riemann server.

C:\python\site-packages\bernhard\__init__.pyc in write(self, message)
     50             rxlen = struct.unpack('!I', self.sock.recv(4))[0]
     51             # Rx entire response
---> 52             response = self.sock.recv(rxlen, socket.MSG_WAITALL)
     53             return response
     54         except (socket.error, struct.error) as e:

AttributeError: 'module' object has no attribute 'MSG_WAITALL'

This is a known issue described here with a potential fix:
https://bugs.launchpad.net/myconnpy/+bug/437972
https://github.com/dtmilano/AndroidViewClient/issues/90

**Comment by banjiewen** [comment]
The fix proposed in that ticket looks reasonable to me. Do you mind writing it up?

**Comment by banjiewen** [comment]
PR merged and 0.2.1 deployed.

**Comment by npezolano** [comment]
Missed a variable declaration, sorry about that!
