### ISSUE TITLE
Numeric custom attributes not available

### ISSUE THREAD

**Issue by assafmilman** [banjiewen/bernhard#21]
This is more of a feature request than an issue.
From what I see all custom attributes are cast to string, while others fields (TTL) are defined as int64. 
Any chance to allow sending numeric fields to Riemann?

**Comment by banjiewen** [comment]
[That's a Riemann "feature", actually][1], so you'll have to go talk to Kyle. Sorry!

[1]: http://riemann.io/howto.html#custom-event-attributes
